### ISSUE TITLE
Element can't be found

### ISSUE THREAD

**Issue by martinmineo** [kyleissuper/WhatsBlaster#3]
It seems that Web WhatsApp elements have changed, see the error

```
Traceback (most recent call last):
  File "/Users/----/workspace/WhatsBlaster/WhatsBlaster.py", line 69, in <module>
    "Hello!"
  File "/Users/----/workspace/WhatsBlaster/WhatsBlaster.py", line 23, in send_message
    search = driver.find_element_by_css_selector("input.input-search")
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 589, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"input.input-search"}
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by kyleissuper** [comment]
Fixed: 34321c7
